### ISSUE TITLE
No need to do this convertion

### ISSUE THREAD

**Issue by sergioviniciuss** [dominickolbe/weather-cli#125]
https://github.com/dominickolbe/weather-cli/blob/3b41c320a9a2c1d032fecdc91eb42e7f637141fe/src/index.js#L21

Hey.. you could pass this query parameter: &units=metric in the api url and then you don't need to convert this yourself🤪

I miss working with you buddy! 😁

**Comment by dominickolbe** [comment]
Thanks for pointing out buddy. It's fixed!
